### ISSUE TITLE
Use JSON pointers for validation results

### ISSUE THREAD

**Issue by smhc** [openapi4j/openapi4j#101]
**Is your feature request related to a problem? Please describe.**

The current validation error reporting does not specify which item in an array the error is associated with. In my case, I am also interested in 'INFO' results which I collect during validation for later type conversion. This data collection should ideally specify the exact item in the array it is associated with - this is needed because the use of 'anyOf', 'allOf' etc can mean different items in an array can have different schemas.

**Describe the solution you'd like**

I believe the use of 'JSON pointers' instead of the current crumbs string would address the concern. A JSON pointer includes the array index information.

This json/openapi validator appears to use json pointers: : https://github.com/networknt/json-schema-validator

**Describe alternatives you've considered**
Potentially using the custom context data and an 'items' custom validator to attempt to keep track of indexes. However this is unlikely to work properly through oneOf/anyOf/allOf etc.

**Additional context**

JSON pointer RFC: https://tools.ietf.org/html/rfc6901

**Comment by llfbandit** [comment]
Adding array index in `ItemsValidator` is OK.
Adding method to `ValidationItem` to get JSON pointer string for data crumbs is OK too. (new method because of encoding performance (~0 & ~1), data not always JSON and less readable IMO globally).

But I don't get your point about collection schemas (any/all/oneOf). Would you like to know selected schema in valid cases? If so, the module will not. For this, you can use delegation from ValidationData for such need.

**Comment by smhc** [comment]
> But I don't get your point about collection schemas (any/all/oneOf). Would you like to know selected schema in valid cases?

Sorry I wasn't very clear about this. I simply meant the use of polymorphic schemas mean that an item in an array could be various schemas and a given validation 'crumb' doesn't distinguish which element in the array has the problem/association.

I have custom validators for 'format' and 'type' which store INFO results to keep track of which node in the data is which type/format. This works ok for objects, even polymorphic objects, but wouldn't work correctly for polymorphic arrays.

i.e
```yaml
components:
  responses:
    sampleObjectResponse:
      content:
        application/json:
          schema:
            type: array
             items:
                oneOf:
                   - $ref: '#/components/schemas/simple'
                   - $ref: '#/components/schemas/complex'
  …
components:
  schemas:
    simple:
      type: array
      items:
          type: boolean
    complex:
      type: array
      items:
          oneOf:
             type: string
             type: number
```

An error or 'INFO' result without associate indexes could be a boolean, string or a number.  There's no current way to know which indexes it is referring to.

**Comment by llfbandit** [comment]
Are you able to validate this on your side too?

`dataJsonPointer()` has been added to `ValidationItem`.

**Comment by smhc** [comment]
Thanks, this seems to work well.
I think the leading "/" should be removed however. This is particularly true for header, path and query param results (although can be avoided by calling the data crumbs function for those)

 It would also be ideal if 'body' was replaced with '#', or '$', this seems to be more conventional. ie from the RFC:

#/foo/0

Although I have seen various examples of different formats.

**Comment by llfbandit** [comment]
You are right about the optional leading "/", I forgot this case.

The output is fine to me, I prefer keep JSON string representation instead of URI.
Since, this is exactly the same with the leading "#", users can create themselves URI object if needed.

A change has been pushed to check if there's at least one crumb for the leading "/".

**Comment by smhc** [comment]
Thanks. I didn't really notice any difference with the latest change. However I am not calling dataJsonPointer for header/path/query validation items so I am not affected.
Happy to close this issue.
