### ISSUE TITLE
oneOf validator should not report all validation errors if no matching schema

### ISSUE THREAD

**Issue by smhc** [openapi4j/openapi4j#102]
**Describe the bug**
The 'oneOf' validator currently reports all failures of non-matching schemas when there are no matches:

https://github.com/openapi4j/openapi4j/blob/c3be565b9530337b5768e81cc6f7cb3ab354c0e4/openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/OneOfValidator.java#L67

I can understand the rationale behind this - it makes it somewhat easier to debug the reason the intended schema didn't match. However considering that a 'oneOf' validator is intentionally meant to fail to match everything (but one) it outputs a lot of misleading errors. I think the original single error of "didn't match one of" is more correct.

If you do wish to keep this in, would it be possible to only add the ERROR severity results and not the WARN or INFO severity? I use the 'INFO' results to keep track of the **matching** data model and it is problematic when there are entries for all the non-matching schemas recorded.

**To Reproduce**

1. Use a oneOf schema that doesn't match the model
2. Log 'INFO' severity results in each of the 'oneOf' candidates
3. See that erroneous INFO level results are output 

**Expected behavior**

Either;
- No error results for non-matching oneOf schemas, or
- No INFO and WARN level results for non-matching oneOf schemas

**Comment by llfbandit** [comment]
This is working as intended. Errors are only reported when oneOf fails to select a single schema.

You must check the result with `isValid()` method. In your case, logging info is not a problem as you can filter items by severity. Maybe there's room for improvement where I can add `getItems(Severity)` and `getItems(EnumSet<Severity>)` methods directly.

**Comment by smhc** [comment]
> Errors are only reported when oneOf fails to select a single schema.

Yes, but it reports all errors (and warnings + info) for all the mismatched schemas. I am still using the results even if the overall result isn't valid (admittedly this is somewhat questionable).

I rely on the fact the logged INFO results are discarded if it doesn't match. But with this scenario the results aren't discarded, they are aggregated instead. So for example;

```yaml
Pet:
 oneOf:
   $ref: Dog
   $ref: Cat
```

I (effectively) log INFO level results of "is a cat!" and "is a dog!" for each oneOf entry, relying on the fact it will be popped off and discarded if it doesn't match, leaving only the matching one in the results. If neither match I expect there to be neither 'is a cat!' or 'is a dog!' in the results.

With the current code I have **both** "is a cat!" and "is a dog!" when it matches neither.

Does it really make sense to log results for non-matched schemas when the intention is that it shouldn't match? I think the net result is very confusing. Majority of the non-matching "errors" aren't errors but simply a way of excluding each schema from the intended target. I do think the original code of logging a single 'no match' error is cleaner.

At the very least I don't think the INFO and WARN level results should be logged, as they didn't contribute to the fact there was no match. They are informational results that are non-applicable as the schema didn't actually match, so they should be discarded. i.e at the very least the code should be changed to:

```java
      for (ValidationResults result : resultsOnError) {
             if (result.gt(WARN) {        
                validation.add(validation.results().crumbs(), result);
             }
      }
```

**Comment by llfbandit** [comment]
Yes, your intention was very clear! :)

After a bit of reflexion, I don't see much usable cases to report items lower than `error` severity. Also, I do want to keep things simple to use. Time will tell...

Results are now striped and only errors are reported.
Also, this issue is expanded to all collection schema to make this consistent.

Can you check the changes your side?
You should have much more sub info to log than me.

Thanks in advance.

**Comment by smhc** [comment]
Thank you for the changes, it seems to work as expected. Although I don't have thorough test cases for the scenario.
