### ISSUE TITLE
Stackoverflow when reading OpenAPI spec with recursive data structure

### ISSUE THREAD

**Issue by tadhgpearson** [openapi4j/openapi4j#106]
When reading an OpenAPI 3 YAML specification file, the following exception is thrown

```
java.lang.StackOverflowError
	at com.fasterxml.jackson.databind.util.TokenBuffer$Segment.append(TokenBuffer.java:2124)
	at com.fasterxml.jackson.databind.util.TokenBuffer._appendFieldName(TokenBuffer.java:1368)
	at com.fasterxml.jackson.databind.util.TokenBuffer.writeFieldName(TokenBuffer.java:748)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:327)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:328)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:328)
	at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:39)
	at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:20)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3900)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3853)
	at org.openapi4j.parser.model.AbsRefOpenApiSchema.copy(AbsRefOpenApiSchema.java:63)
	at org.openapi4j.parser.model.AbsOpenApiSchema.copyField(AbsOpenApiSchema.java:92)
	at org.openapi4j.parser.model.v3.Schema.copyContent(Schema.java:664)
	at org.openapi4j.parser.model.v3.Schema.copyContent(Schema.java:16)
	at org.openapi4j.parser.model.AbsRefOpenApiSchema.copy(AbsRefOpenApiSchema.java:71)
	at org.openapi4j.parser.model.AbsOpenApiSchema.copyMap(AbsOpenApiSchema.java:117)
	at org.openapi4j.parser.model.v3.Schema.copyContent(Schema.java:665)
	at org.openapi4j.parser.model.v3.Schema.copyContent(Schema.java:16)
```

... last 4 lines are looped to the end of the stack trace

**To Reproduce**
1.  Take the following simple Open API schema

```
openapi: 3.0.0
info:
  title: Control Center
  version: 0.1.0
paths:
  /applications:
    get:
      summary: Retrieve all applications
      operationId: retrieveApplications
      responses:
        200:
          description: List of applications response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApplicationSummary"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    ApplicationSummary:
      type: object
      required: [name]
      properties:
        name:
          type: string
    Error:
      type: object
      required: [type, statusCode]
      properties:
        type:
          type: string
        detail:
          type: string
        statusCode:
          type: integer
        instance:
          type: string
          format: url
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
```

2.  Create a new Maven project with this schema validator as a dependency
    ``` 

<dependency>
      <groupId>org.openapi4j</groupId>
      <artifactId>openapi-operation-validator</artifactId>
      <version>0.9</version>
    </dependency>
```

3.  Make a new class to parse the input as follows

```
public class OpenAPIValidator {

  private static final ClassLoader classLoader = OpenAPIValidator.class.getClassLoader();

  private final OpenApi3 spec;

  public OpenAPIValidator(OpenApi3 spec) {
    this.spec = spec;
  }

  /**
   * @param pathToSpecFile Relative location of your OpenAPI specification in the resources folder
   * @return A ready-to-go OPEN API validator
   */
  public static OpenAPIValidator from(String pathToSpecFile) {
    String specFilePath = classLoader.getResource(pathToSpecFile).getFile();
    File specFile = new File(specFilePath);
    final OpenApi3Parser parser = new OpenApi3Parser();
    final OpenApi3 spec;
    try {
      spec = parser.parse(specFile, true);
      return new OpenAPIValidator(spec);
    } catch (ResolutionException e) {
      throw new IllegalArgumentException("Could not find OpenAPI specification file at " + specFilePath, e);
    } catch (ValidationException e) {
      String message = "The OpenAPI specification file at " + pathToSpecFile + " is not valid: " + e.getMessage();
      throw new IllegalArgumentException(message, e);
    }
  }
```

4. Invoke the new class in a test like so:
  `OpenAPIValidator underTest = OpenAPIValidator.from("docs/identity-cloud-control-center.yaml");`

**Expected behavior**
I should now be able to validate input against my OpenAPI schema

**Additional context**
Open API schema is considered valid by Swagger Editor

**Reproducer**
?

**Comment by tadhgpearson** [comment]
When I comment out the last element of the API schema (the nested "error" object), it works fine

**Comment by llfbandit** [comment]
Hi and welcome,

Thanks for the report, I'll dig into it from tomorrow.

**Comment by llfbandit** [comment]
Provided code does not lead to the current error. I assume you're using `toNode` or `copy` methods with `followRefs` set to true to reproduce it. By setting `followRefs`, you're trying to include content from $ref instead of keeping $ref attribute.
Anyway, I'll try to make guards on this to prevent those exceptions but generally it's way better to keep it false when serializing models to handle/read or use them afterwards.

**Comment by tadhgpearson** [comment]
Thanks @llfbandit  for the welcome and quick response

> I assume you're using toNode or copy methods with followRefs set to true to reproduce it.

I don't know what you mean....
The code I'm using above reproduces the problem for me... let me dump it into a public repo for you (when i get a chance, I have 2 children in lockdown here, so not much computer time) so that we can be sure we're on the same page

**Comment by llfbandit** [comment]
Sure, and meanwhile stay safe!

**Comment by llfbandit** [comment]
Closing the issue due to inactivity.
Feel free to reopen it if you have further details to share.

**Comment by MarcoPriebe** [comment]
I'm also seeing the mentioned exception when validating a spec with a cyclic reference in a schema component. While I'm able to parse the given spec without an exception it leads to a StackOverflowError when calling the `org.openapi4j.parser.validation.v3.OpenApi3Validator.validate(api)` method.

**Comment by llfbandit** [comment]
I'm unable to reproduce it with v1.0. There's no more recursion code in the toolset since PR #107.
Please upgrade to this version and give me your feedback.
If you still reproduce it, there must be something else that is not described.

Here's the code I used to confirm:
```
URL specPath = getClass().getResource("/model/v3/oai-integration/looping-ref-model.yaml");
OpenApi3 api = new OpenApi3Parser().parse(specPath, true);
Operation op = api.getPath("/applications").getGet();
System.out.println(op.getOperationId()); // prints retrieveApplications
```

**Comment by MarcoPriebe** [comment]
I'm sorry. I made a mistake. I'm also just working on an example to nail down the error within a minumum example. Pls try 
```
URL specPath = getClass().getResource("/model/v3/oai-integration/looping-ref-model.yaml");
OpenApi3 api = new OpenApi3Parser().parse(specPath, true);
Path path = api.getPath("/applications")
Operation op = path.getGet();
System.out.println(new OperationValidator(api,path,op));
```
Thanks for your quick response :slightly_smiling_face:

**Comment by MarcoPriebe** [comment]
I just saw I was still working with v0.9. The Validation works fine with v1.0. So pls keep the Issue closed. Sorry for the trouble!

**Comment by tadhgpearson** [comment]
Just validated that your fix does also fix my case, thanks!

I've posted code to reproduce the now fixed issue at https://github.com/tadhgpearson/recursive-definition-demo ... if you want to take it and add it to your regression tests
