### ISSUE TITLE
Severity WARNING is excessive for format: uuid

### ISSUE THREAD

**Issue by tadhgpearson** [openapi4j/openapi4j#110]
**Describe the bug**
The format `uuid`, while currently not officially supported in the Open API 3.0 spec, is widely used and supported. Producing a validation warning when it occurs diminishes the usefulness of the specification in other tools and adds noise to the results.

**To Reproduce**
1. Define a swagger response object, with type: string and format: uuid such as the Success object here: https://github.com/tadhgpearson/recursive-definition-demo/blob/master/src/main/resources/recursive-definition.yaml
2. Define a response containing a UUID, such as `{"id":"fa3a04be-1a06-449b-b209-d920eb6c6e5b"}`
3. Validate it. You will receive the following warning `body.id: Format 'uuid' is unknown, validation passes. (code: 1008)
From: body.id.<format>`

**Expected behavior**
Validation should pass without warnings, since uuid is widely supported.

**Additional context**

* Open API follows JSON Schema, and newer versions of JSON Schema support uuid: https://json-schema.org/draft/2019-09/json-schema-validation.html
Thus we should expect uuid support to be official soon
* A wide variety of OpenAPI / Swagger tooling supports uuid format, including IntelliJ, Swagger Editor, Swagger Codegen and Swagger UI

**Reproducer**

**Comment by llfbandit** [comment]
Thank you for the report, this now included in next version.
You can use it in current 1.0.2-SNAPSHOT version.
