### ISSUE TITLE
Cannot validate response with empty body if there is a default response with a body.

### ISSUE THREAD

**Issue by fabiohecht** [openapi4j/openapi4j#113]
**Describe the bug**

**To Reproduce**

1. Create a schema with the following responses:
```
    responses:
      201:
        description: Resource is successfully created
      default:
        description: Unexpected error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
````
2. Call the `validate()`method of the `RequestValidator` with arguments Response, Path, Operator. The response has status 201, body null, and no Content-Type header (complying with the schema above).

3. Validation fails with message: Invalid response. [Body content type cannot be determined. No 'Content-Type' header available. (code: 202)] 

**Expected behavior**
201 must have no body (and no Content-Type). All other responses must have a body with Content-Type application/json and match the schema.

**Comment by llfbandit** [comment]
Hi and welcome,

In fact, the only required field is `description` for any response Object. 

I'll check this in few hours. Scanning source code on mobile phone isn't really efficient ;)

**Comment by fabiohecht** [comment]
Hey, thanks for the quick response and fix. I confirm this solves the issue. Cheers, Fabio.
