### ISSUE TITLE
Schema validation for Response

### ISSUE THREAD

**Issue by adeliagoncalves** [openapi4j/openapi4j#115]
I already validate my request using schema validator but what I really need is to validate a response.
My spec:

/score:
    post:
      tags:
        - goal
      summary: 
      operationId: 
      consumes:
        - application/json
      parameters:
        - in: 
          name: 
          description: 
          schema:
            $ref: '#/definitions/Request'
responses:
        '200':
          description: Successful Request
          schema:
            $ref: '#/definitions/Response'

I tried to use the same approach to validate schema for response but getResponse("200").getSchema didn't work.
Is it possible to use the same approach or should use the requestValidator (response)?

**Comment by llfbandit** [comment]
Hi and welcome,

To validate request or response, you should use `RequestValidator` object with `validate` methods.
As an alternative you can directly use `OperationValidator` object too.

`RequestValidator` is recommended.
