### ISSUE TITLE
OpenApi3Validator doesn't consider path parameters

### ISSUE THREAD

**Issue by Walter-Link** [openapi4j/openapi4j#116]
**Describe the bug**
The OpenApi3Validator doesn't consider parameters declared in the path object, this results in wrong validation errors.

**To Reproduce**
1. Read the following OpenAPI spec:
{
  "openapi" : "3.0.0",
  "info" : {
    "description" : "REST Service for requesting price and stock",
    "title" : "RequestService",
    "version" : "1.0"
  },
  "paths" : {
    "/getPrice/{company}/{supplier}" : {
      "parameters" : [ {
        "required" : true,
        "style" : "simple",
        "in" : "path",
        "name" : "company"
      }, {
        "required" : true,
         "style" : "simple",
        "in" : "path",
        "name" : "supplier"
      } ],
     "summary" : "Request price",
      "post" : {
        "summary" : "Request price",
        "parameters" : [ {
          "style" : "simple",
          "in" : "header",
          "name" : "Content-Length"
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : { }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Success response",
            "content" : {
              "application/json" : { }
            }
          }
        }
      }
    }
  }
}

2. validate it using OpenApi3Validator.instance().validate(model);
3. The OpenApi3Validator (openapi4j version 1.0.1) complains:

OpenApi3 validation failure
Validation error(s) :
From: servers.url
name: Path parameter 'company' in path '/getPrice/{company}/{supplier}' is expected but undefined (code: 124)
From: name

**Expected behavior**
I expect the validator to validate the model without errors

**Additional context**

The problem occurs in class OpenApiValidator.
The method checkOperationsParams should also consider the path parameters not only the operation parameters!

**Reproducer**
Please fill a reproducer for debugging purpose.

**Comment by llfbandit** [comment]
Hi and welcome,

Thanks for the report.
Somehow, the `Path item` parameters are not propagated during Operation validation.

I'm on it.

**Comment by llfbandit** [comment]
This is now fixed in 1.0.2-SNAPSHOT.
Are you able to validate the changes ?

Thanks for your feedback.

**Comment by Walter-Link** [comment]
The problem seems to be fixed.
Thank you for your work and your fast response.


Am Fr., 26. Juni 2020 um 20:20 Uhr schrieb llfbandit <
notifications@github.com>:

**Comment by llfbandit** [comment]
You're welcome.
v1.0.2 is about to land now including those changes.
