### ISSUE TITLE
Disable server validation

### ISSUE THREAD

**Issue by jonasborn** [openapi4j/openapi4j#124]
**Is your feature request related to a problem? Please describe.**
When checking the server a request, is there any chance to disable the server validator?
I'm using a servlet based solution befind a load balancer, so the server URL is not the one used in my specs.

**Describe the solution you'd like**
A possibility to disable some vaildators.

**Describe alternatives you've considered**
At the moment I'm using a regex function to replace the current host and port from the request with a fiexed variable. Same variable is used with a new server created after all others are removed.

**Comment by llfbandit** [comment]
Hi and welcome,

I assume you're using `RequestValidator#validate(Request)`.

Two early thoughts:
- What about removing server description if you don't use it?
- What about setting Path and Operation in your servlet to get rid of regex on each request?

**Comment by jonasborn** [comment]
Hey, thanks for the fast response ^^

- Removing the server description is not possible because of their use in some clients. Removin all servers by clearing the servers array of the OpenApi3 object also creates an exception. The only way I see here is manually parsing and alterning the file before loading them with the OpenApi3Parser.

- Validating by using Path and Operation seems to work - Thanks ^^ Just took some time to understand, that Path and Operation are used directly from the parsed spec.

**Comment by llfbandit** [comment]
You're welcome.
So, all good? Can we close the issue?

**Comment by jonasborn** [comment]
Yes, all up and running.
Thanks
