### ISSUE TITLE
OpenApi3Validator doesn't resolve server variables

### ISSUE THREAD

**Issue by Walter-Link** [openapi4j/openapi4j#125]
**OpenApi3Validator doesn't resolve server variables**

I tried to parse and validate the example file uspto.yaml from the official OpenAPI website (https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0/uspto.yaml)

OpenApi3 validation failure
Validation error(s) :
servers.url: Invalid URL '{scheme}://developer.uspto.gov/ds-api{scheme}://developer.uspto.gov/ds-api' (code: 108)
From: servers.url

	at org.openapi4j.parser.validation.v3.OpenApi3Validator.validate(OpenApi3Validator.java:28)
	at org.openapi4j.parser.OpenApi3Parser.parse(OpenApi3Parser.java:41)
	at org.openapi4j.parser.OpenApi3Parser.parse(OpenApi3Parser.java:17)
	at org.openapi4j.parser.OpenApiParser.parse(OpenApiParser.java:53)
	at org.openapi4j.parser.OpenApiParser.parse(OpenApiParser.java:37)

**To Reproduce**
To reproduce the behavior, execute the following code:

		URL url = new URL("https://github.com/OAI/OpenAPI-Specification/raw/master/examples/v3.0/uspto.yaml");
		OpenApi3Parser parser = new OpenApi3Parser();
		parser.parse(url, true);

**Expected behavior**
At least the few examples from the OpenApi website should be parsed and validated without problems.

**Hint**
I think you should first replace the variables before checking the URL in the ServerValidator.

**Comment by llfbandit** [comment]
Hi,

This is already fixed with the related/duplicated issue #121 you opened.
Check it out with 1.0.3-SNAPSHOT.
