### ISSUE TITLE
Handle validating against enum types

### ISSUE THREAD

**Issue by nathanmalloch** [openapi4j/openapi4j#150]
**Is your feature request related to a problem? Please describe.**  
When suing the enum spec, validating for this is ignored. Ex. I will define a request schema to look like this:
```
"properties": {
      "item": {
            "type": "string",
            "enum": [
                   "A",
                   "B",
                   "C"
            ]
     }
 }
```
however I can run the request with 
```
body = {
     "item": "D"
}
```
and the validation does catch it.

**Describe the solution you'd like**  
I would like to have the enums validated

**Comment by llfbandit** [comment]
Hi and welcome,

The issue seems invalid. 
Can you provide a reproducer ?

**Comment by nathanmalloch** [comment]
sorry for the wait. here is an example of what I am seeing:
this is the openApi.json. and the problem I am seeing is that the
highlighted section doesn't validate. for either the order ref or the
enum_values section

{
  "openapi": "3.0.1",
  "info": {
    "title": "Service",
    "version": "1.0.0"
  },
  "paths": {
    "/test-endpoint": {
      "post": {
        "parameters": [
          {
            "$ref": "#/components/parameters/SearchString"
          },
          {
            "$ref": "#/components/parameters/Limit"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SearchObject"
              }
            }
          }
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "values": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "values": [{
                    "id": 23,
                    "name": "Michael Scott"
                  }]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "SearchString": {
        "in": "query",
        "name": "search_string",
        "schema": {
          "type": "string"
        },
        "required": false
      },
      "Limit": {
        "in": "query",
        "name": "limit",
        "schema": {
          "type": "integer",
          "default": 50
        },
        "required": false
      }
    },
    "schemas": {
      "Order": {
        "type": "string",
        "enum": [
          "asc",
          "desc"
        ],
        "default": "asc"
      },
      "FilterString": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "FilterInteger": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "SearchObject": {
        "type": "object",
        "properties": {
          "enum_values": {
            "type": "object",
            "properties": {
              "filter_params": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "test1",
                    "test2"
                  ]
                },
                "maxItems": 2
              },
              "order": {
                "$ref": "#/components/schemas/Order"
              }
            }
          }
        }
      }
    }
  }
}
