### ISSUE TITLE
Pattern feature in OpenAPI 3.0.0 is not validating the RegEx 

### ISSUE THREAD

**Issue by bachi317** [openapi4j/openapi4j#151]
**Version**  
1.0.4

**Describe the bug**  
When using the pattern option for a string field in OpenAPI 3.0.0 validation is not rejecting the requests.
Here is my field declaration

InitiatorReferenceId:
      description: A unique identifier to identify each of the bulk payment request submitted by the initiator which will be used for duplicate checking.
      type: string
      pattern: '^(?! )[A-Za-z0-9]*$'
      minLength: 1
      maxLength: 32
      example: 'abc123-def-345-zrt'

**Expected behavior**  
When I pass the value " @#$@#kjlkjdfs" with leading space and special characters I would expect to reject it. But its passing the validation. 

**Additional context**  
Can you please confirm if using the "pattern" feature in OpenAPI works with this jar file? Thanks. 

**To Reproduce**  
1. Use any swagger with the above declaration.
2. Submit a value with space and special characters like " @#$@#kjlkjdfs"
3. You should get validation passed

**Comment by llfbandit** [comment]
Hi and welcome,

Yes, 'pattern' keyword is supported. I suppose your schema is not triggered.

**Comment by bachi317** [comment]
Greetings, 

Yes the schema wasn't triggered properly not sure why. Now its all looking good. Thanks for the quick reply :-).
