### ISSUE TITLE
Some of the optional fields when using oneOf are not being validated

### ISSUE THREAD

**Issue by bachi317** [openapi4j/openapi4j#154]
**Version**  
1.0.4

**Describe the bug**  
We have an api to create instructions using POST. It have 2 elements "createMetadata" with some fields in it and "createInstruction" with "oneOf" feature in OpenAPI 3 using 4 different objects. 
For this issue, I am using the DirectBulkCreate object under "createInstruction" oneOff feature. The request has a "creator" element with "creatorReference" as an optional element under which "name", "code", "reference" are 3 optional element with string as datatype. Then  there is an "instructions" element which is an array, under which we have "acceptor" and an optional "acceptorReference" with  "name", "code", "reference" are 3 optional elements with string as datatype.

Now when I pass an integer value for "name" under "creatorReference" the validation is not throwing error. Here is the sample payload.

{
  "createMetadata": {
    "initiatorReferenceId": "123",
    "type": "directCreate",
    "authNumber": "123456",
    "createDate": "2020-11-01",
    "individual": false,
    "createCount": 3,
    "numberOfSignatories": 1,
    "hashTotal": "345678"
  },
  "createInstruction": {
       "creator": {
      "idNumber": "0987654321123456",
      "name": "efgh"
    },
    "creatorReference": {
      **"name": 123,**
      "code": "code",
      "reference": "ref"
    },
    "instructions": [
      {
        "value": 123,
        "acceptor": {
          "idNumber": "1234567890123456",
          "name": "abcd"
        },
        "acceptorReference": {
          "name": "name",
      "code": "code",
      "reference": "ref"
        }
      }
    ]
  }
}

But if I send an integer value for the "name" under "acceptorReference" the validation is kicking off and sending back the below errors.

"body.createInstruction.instructions.0.acceptorReference.name: Type expected 'string', found 'integer'."
"body.createInstruction.creatorReference.name: Type expected 'string', found 'integer'."

Here is the payload

{
  "createMetadata": {
    "initiatorReferenceId": "123",
    "type": "directCreate",
    "authNumber": "123456",
    "createDate": "2020-11-01",
    "individual": false,
    "createCount": 3,
    "numberOfSignatories": 1,
    "hashTotal": "345678"
  },
  "createInstruction": {
       "creator": {
      "idNumber": "0987654321123456",
      "name": "efgh"
    },
    "creatorReference": {
      **"name": 123,**
      "code": "code",
      "reference": "ref"
    },
    "instructions": [
      {
        "value": 123,
        "acceptor": {
          "idNumber": "1234567890123456",
          "name": "abcd"
        },
        "acceptorReference": {
          **"name": 123,**
      "code": "code",
      "reference": "ref"
        }
      }
    ]
  }
}

**Expected behavior**  
We expect the validation to be working for all the optional fields as well whenever they supplied. 

**Additional context**  
I am attaching the swagger for you to try. 

**To Reproduce**  
1. Attached the swagger that we are using for the createAPI. Import that onto your local eclipse or equivalent environment.
2. Pass the below payload to the framework along with the above swagger.
{
  "createMetadata": {
    "initiatorReferenceId": "123",
    "type": "directCreate",
    "authNumber": "123456",
    "createDate": "2020-11-01",
    "individual": false,
    "createCount": 3,
    "numberOfSignatories": 1,
    "hashTotal": "345678"
  },
  "createInstruction": {
       "creator": {
      "idNumber": "0987654321123456",
      "name": "efgh"
    },
    "creatorReference": {
      "name": 123,
      "code": "code",
      "reference": "ref"
    },
    "instructions": [
      {
        "value": 123,
        "acceptor": {
          "idNumber": "1234567890123456",
          "name": "abcd"
        },
        "acceptorReference": {
          "name": "name",
      "code": "code",
      "reference": "ref"
        }
      }
    ]
  }
}
3. You should notice validation successful instead of a validation failure message.

**Reproducer**  
N/A
[CreateAPI.yaml.zip](https://github.com/openapi4j/openapi4j/files/5472383/CreateAPI.yaml.zip)

**Comment by llfbandit** [comment]
OneOf keyword validates each schema one by one. Use AllOf if you need to get all valid schemas.
Closing the issue since this is not related to the tool.
