### ISSUE TITLE
Convenience methods to support easy response validation

### ISSUE THREAD

**Issue by aburmeis** [openapi4j/openapi4j#156]
I would like to validate request and response in a test. For the request this is supported very well. The Response can be validated using the `OperationValidator` but to use it I would need a `Path` and `Operation` object wich is typically managed by the `RequestValidator`.

A handy solution would be the following new method for `RequestValidator`:

    public OperationValidator getValidator(Request request) throws ValidationException {
      Pattern pathPattern = PathResolver.instance().findPathPattern(pathPatterns.keySet(), request.getPath());
      if (pathPattern == null) {
        throw new ValidationException(String.format(INVALID_OP_PATH_ERR_MSG, request.getURL()));
      }
      Path path = pathPatterns.get(pathPattern);
      Operation operation = path.getOperation(request.getMethod().name().toLowerCase());
      if (operation == null) {
        throw new ValidationException(String.format(INVALID_OP_ERR_MSG, request.getURL(), request.getMethod().name()));
      }
      return getValidator(path, operation);
    }

I am pretty sure, using are some refactoring the resulting code duplication in `RequestValidator` could be minimized.
With such an approach I could do the following validation:

    OperationValidator opValidator = new RequestValidator(api).getValidator(request);
    ValidationData<?> validation = new ValidationData<>();
    opValidator.validateHeaders(response, validation);
    opValidator.validateBody(response, validation);
    if (!validation.isValid()) {
      throw new ValidationException(INVALID_RESPONSE_ERR_MSG, validation.results());
    }

Even better the `OperationValidator` could offer this as convenience methods:

    public void validate(Response response) throws ValidationException {
      validate(response, new ValidationData<>());
    }

    public void validate(Response response, ValidationData<?> validation) throws ValidationException {
      validateHeaders(response, validation);
      validateBody(response, validation);
      if (!validation.isValid()) {
        throw new ValidationException(INVALID_RESPONSE_ERR_MSG, validation.results());
      }
    }

With that the validation get a one-liner:

    new RequestValidator(api).getValidator(request).validate(response);

As I am not sure about your design considerations it is also possible to add the convenience methods for response validation directly to `RequestValidator` but it would need one parameter more for each method:

    public void validate(Response response, Request request) throws ValidationException

    public void validate(Response response, Request request, ValidationData<?> validation) throws ValidationException

**Comment by bdremynoel** [comment]
Hi,

Thanks for opening an issue!

I don't have much time to add this QoL methods right now but I'll definitely have a look!
Don't know (remember?) why this is not available yet...

**Comment by aburmeis** [comment]
@bdremynoel If you could decide where to put the methods (`RequestValidator` only or combination with `OperationValidator`) I should be able to create a PR.

**Comment by llfbandit** [comment]
Both locations seem fine since they are complementary to each other.
`OperationValidator` validates all aspects of requests and responses and `RequestValidator` is on top to handle cache for paths and validators.
