### ISSUE TITLE
Incorrect path pattern for path parameter

### ISSUE THREAD

**Issue by dalv666** [openapi4j/openapi4j#161]
**Version**  
Version  1.0.5

**Describe the bug**  
Incorrect path pattern for path parameter. It could lead to incorrect path selection in validation phase. 

### Example:
**paths:**
- _items/{id}_
- _items/_

**generated path patterns:**

- for _items/{id}_ -> **_"^\Q/items/\E(?<id>[^\/]+)$"_**
- for _items/_ -> **_"^\Q/items/\E$"_**

So, for `items/` request both patterns are valid and validation will occur in random way. 

According to [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#parameter-object) path parameters are required by default:

> Determines whether this parameter is mandatory. If the [parameter location](#parameterIn) is `"path"`, this property is **REQUIRED** and its value MUST be `true`. Otherwise, the property MAY be included and its default value is `false`.

I suggest to change path parameter regExp group from optional to required. 
In this [line](https://github.com/openapi4j/openapi4j/blob/master/openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/util/PathResolver.java#L29) from **_">[^\\/]*)"_** to  **_">[^\\/]+)"_**.

And also suggest think about throwing exception when there is more than one matches.  

**Expected behavior**  
Requests path:
- _items/{id}_
- _items/_

are identified as different paths for validation.

**Additional context**  
Validation is depended on path key order in a Set. But every time it could be different, also JIT optimization could influence on key selection.

**To Reproduce**  
1. Create specification with the next paths and different schemas:
- items/{id}
- items/
2. Make a lot of request validation for path:
- items/

**Reproducer**  
Please fill a reproducer for debugging purpose.

**Comment by llfbandit** [comment]
Hi,

Thanks for the report. I'll take a look at this regex.

Regarding path precedence, OAI spec explains it already [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#paths-object).
So this could be definitely an improvement, but I've no time to provide this feature for now.

About key order, I need to double check too. LinkedHashMap should used for sure.

**Comment by llfbandit** [comment]
I changed the regExp to the suggested one. Fixed in latest snapshot.

I created (https://github.com/openapi4j/openapi4j/issues/166) to track pattern collisions.

Feel free to re-open the issue if you still experience it.
