### ISSUE TITLE
Creating schema references programatically

### ISSUE THREAD

**Issue by marchof** [openapi4j/openapi4j#162]
Hi,

thanks for the great library! It is very helpful to generate and validate OpenAPI specifications programmatically.

To improve my OpenAPI definitions I would like to share schemas for multiple responses under `#/components/schemas`

Is it possible to programmatically set a schema reference which also works with response validation?

Please excuse me if this tracker is the wrong place to ask questions.

Best Regards,
-marc

**Comment by llfbandit** [comment]
You're serializing schemas from models right ?
I guess you can by adding your schema under `#/components/schemas` and add reference to the dedicated response schema model via `setReference` method.

**Comment by marchof** [comment]
Actually the schemas are also created programmatically and set:

    OpenApi3 api = new OpenApi3();
    api.getComponents().setSchemas(generateSchemas());

This part works. I struggle with `Schema.setReference()`. What are the required parameters here? It looks like to me that these parameters only make sense in case of parsing.

**Comment by llfbandit** [comment]
`context` holds the reference registry, `url` is the base url (mostly useful in case of multiple documents) you can put your document location and `ref` is the string that will be serialized.

You should setup the context right after creating `OpenApi` object;
```
OAI3Context context = new OAI3Context(url); // any valid url syntax should do the job in your case
api.setContext(context);
```

**Comment by marchof** [comment]
I tried this, but for me `new OAI3Context(url)` actually tries to load content from the URL -- which does not (yet) exist because I'm just generating the definition.

So I tried the other constructor `OAI3Context(baseUrl, baseDocument)`. In this case the URL is not loaded but the baseDocument is always incomplete during the process of building and I end up with NPEs during response validation.

**Comment by marchof** [comment]
I think I found a work around. After programmatic assembly of the `OpenApi3` instance in need to do the following conversion:

    OpenAPI3 --> JsonNode --> OpenApi3

Like with this code:

    // Serialize/Deserialize to properly wire references
    OAI3Context context = new OAI3Context(DUMMY_URL, api.toNode());
    api = TreeUtil.json.convertValue(context.getBaseDocument(), OpenApi3.class);
    api.setContext(context);

The newly created OpenAPI3 instance then has the references properly wired and can be used for validation.

I wonder whether there is a better "official" way?

**Comment by llfbandit** [comment]
Parser module expects to start from a base.
So excepted starting from an empty (but existing) file to avoid this round-trip, I think there won't be more solutions in your case.

**Comment by marchof** [comment]
@llfbandit Ok, thanks for your support! The workaround is ok for me now. If I find some time I'll try to dig deeper and may find a way to extend openapi4j to allow pure in-memory construction of OpenAPI3 instances with references.

Thanks again your work!
