### ISSUE TITLE
Integer formats not identified in 1.0.5 version openapi4j tool

### ISSUE THREAD

**Issue by kbora123** [openapi4j/openapi4j#164]
**Version**  
1.0.5  

**Describe the bug**  
There was a defect opened up in https://github.com/openapi4j/openapi4j/issues/152
As per the status it is fixed. But I tested in 1.0.5 version and I still see that int64 or int32 format is still not honoured.  

I still see error with 1.0.5 version. The sample schema file contents is given below.

"max_resp_len": {
"minimum": 0,
"type": "integer",
"format": "int64",
"description": "maximum FTP response accepted by client",
"maximum": 4294967295,
"default": 4294967295
}

Validation error(s) :
paths./f_client.put.requestBody.content.application/json.schema.properties.instances.properties.data.properties.max_resp_len.default: Value '4294967295' is incompatible with schema type 'integer' (code: 138)
From: paths./f_client.put.requestBody.content.application/json.schema.properties.instances.properties.data.properties.max_resp_len.default
components.schemas.f_client.max_resp_len.default: Value '4294967295' is incompatible with schema type 'integer' (code: 138)
From: components.schemas.f_client_snort.max_resp_len.default

at org.openapi4j.parser.validation.v3.OpenApi3Validator.validate(OpenApi3Validator.java:28)
at com.cisco.api.external.rest.docs.OpenAPI4jValidationPOCEntireContents.main(OpenAPI4jValidationPOCEntireContents.java:45)

**Expected behavior**  
The above schema error should not be given.  

**Additional context**  

**To Reproduce**  
1. ...
2. ...
3. ...  

**Reproducer**  
Please fill a reproducer for debugging purpose.

**Comment by llfbandit** [comment]
Fixed in latest snapshot.
Feel free to re-open this issue if you still experience it.
