### ISSUE TITLE
Scheme that contains path parameters with minus sign in name fails validation

### ISSUE THREAD

**Issue by drnetua** [openapi4j/openapi4j#165]
**Version**  
1.0.5

**Describe the bug**  
Scheme that contains path parameters with minus sign in name fails validation

Sample: 
```
paths:
  /apath/{user-id}:
    get:
      parameters:
        - $ref: '#/components/parameters/EntityId'
        - name: user-id
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/EntityId'
          description: The ID of the entity.
      responses:
        '200':
          description: The description`
```          

Validation error          
```
OpenApi3 validation failure
Validation error(s) :
paths./apath/{user-id}.name: Path parameter 'user-id' in path '/apath/{user-id}' is unexpected (code: 123)
From: paths./apath/{user-id}.name
```

**Expected behavior**  
No validation errors for path params with minus sign

**Additional context**  
Validation failure cause is `org.openapi4j.parser.validation.v3.PathValidator.PATTERN_PATH_PARAM', that can be fixed with 
```
private static final Pattern PATTERN_PATH_PARAM = Pattern.compile("/\\{([a-zA-Z0-9_-]+)}");
```

**Comment by llfbandit** [comment]
Hi,

Thanks for the report.

Two issues here:

- You set your parameter in query not in path. This is the error reported.
- The regex.

Fixed in latest snapshot.
Feel free to re-open the issue if you still experience it.
