### ISSUE TITLE
Get the path of an operation

### ISSUE THREAD

**Issue by davidecorradini** [openapi4j/openapi4j#170]
**Is your feature request related to a problem? Please describe.**  
From an operation, I would like to access the path it belongs to. For example, when I obtain an `Operation` using `getOperationById(String id)`, I don't have any reference to the context of the operation, e.g. its path.

**Describe the solution you'd like**  
I would like a method `getPath()` in the class `Operation` which returns the corresponding `Path` instance.

**Describe alternatives you've considered**  
No alternative

**Additional context**  
Nothing to add. The explanation should be clear.

**Comment by llfbandit** [comment]
Use `getPathItemByOperationId` on `OpenApi3`.

**Comment by davidecorradini** [comment]
Thank you!
