### ISSUE TITLE
additionalProperties using a $ref are resolved to `false` when calling toNode

### ISSUE THREAD

**Issue by elliott-miller** [openapi4j/openapi4j#21]
**Describe the bug**
When using a JSON ref, it is not possible to get back the additional properties JSON in the schema

**To Reproduce**
```java
import com.fasterxml.jackson.databind.JsonNode;
import org.openapi4j.parser.OpenApi3Parser;
import org.openapi4j.parser.model.v3.OpenApi3;
import org.openapi4j.parser.model.v3.Schema;

import java.nio.file.Files;
import java.nio.file.Path;

public class AdditionalPropertiesBug {
    public static void main(String[] args) throws Exception {
        String openApi =
        "components:\n" +
        "  schemas:\n" +
        "    Messages:\n" +
        "      type: object\n" +
        "      additionalProperties:\n" +
        "        $ref: '#/components/schemas/Message'\n" +
        "    Message:\n" +
        "      type: object\n" +
        "      properties:\n" +
        "        code:\n" +
        "          type: integer\n" +
        "        text:\n" +
        "          type: string";

        Path enumBug = Files.createTempFile("", "");
        Files.write(enumBug, openApi.getBytes());

        OpenApi3 api = new OpenApi3Parser().parse(enumBug.toFile(), false);

        Schema schema = api.getComponents().getSchema("Messages");

        JsonNode jsonNode = schema.toNode(api.getContext(), true);

        System.out.println(jsonNode.toPrettyString());
    }
}
```

The output: 

```
{
  "type" : "object",
  "additionalProperties" : false
}
```

**Expected behavior**
The `additionalProperties` field should be the same as the source document

**Additional context**
I am attempting to use openapi4j to validate JSON examples, from the OpenAPI document and at runtime using https://github.com/networknt/json-schema-validator, any enumerated integer value currently fails

**Comment by llfbandit** [comment]
@elliott-miller Thanks for the report.
0.6-SNAPSHOT will be available soon, are you able to check the provided modification ?

**Comment by elliott-miller** [comment]
Yes no problem, let me know when it's available

**Comment by llfbandit** [comment]
It should be already, snapshot versions are generated for all master valid commits.

**Comment by elliott-miller** [comment]
I can confirm this is fixed in the latest code. Thanks for the fast turn around! I look foward to the 0.6 release :)

**Comment by llfbandit** [comment]
Thank you for the feedback ! Just to let me know, why are you using schema validator from networknt instead of the one provided here ?

**Comment by elliott-miller** [comment]
The code I am working in was already validating with networknt, now that these issues are fixed I will look into using the validator provided here.

**Comment by llfbandit** [comment]
Ok, it's clear now !
