### ISSUE TITLE
Query parameters not marked as required still fail NullableValidator

### ISSUE THREAD

**Issue by pilzm** [openapi4j/openapi4j#31]
**Describe the bug**
Given two query parameters `a` and `b`, both __not__ marked as `required`.
If a request has no `query` string, it will correctly pass the request validation.
However, a request that has a value for `a` but not `b` will fail validation with the message 
```
b.nullable : Null value is not allowed.
```
**To Reproduce**
1. Define two or more non-required query parameters
2. Validate a request with query set to `null` - it will pass
3. Validate a request with query set to empty string - it won't pass
3. Validate a request with query set to `a=1` (where `a` is one of the parameters defined in step 1) - it won't pass

**Expected behavior**
Given two non-required query parameters, I'd expect a request to pass without specifying a value for all parameters.

**Additional context**
The issue seems to be caused by `ParameterValidator#checkRequired`. When the query is `null`, the `paramValues` will be an empty map. 
However, when the query is `""`, the `paramValues` is populated with `null`-values. Similarly, when the query is `a=1`, the map will contain the values  `{a: 1, b: null}`
This causes the function to return `true`, thus marking the null-ish parameter for further validation.
Later on, in the `NullishValidator`, it's correctly recognized that the query parameter is set to `null`

One solution could be to treat `null` values in `paramValues` as unset.

**Reproducer**
[required-params.zip](https://github.com/openapi4j/openapi4j/files/4041011/required-params.zip)

**Comment by llfbandit** [comment]
Confirmed, but because of style triggers this issue applies to a wider scope than query parameters.
This could apply to all parameters (cookie, header, query, path?).

It shouldn't be too difficult to fix it but I will take advange of this issue to ensure to make it globally consistent between a missing parameter and a null set value.

**Comment by llfbandit** [comment]
Could you confirm the resolution from the latest snapshot ?

**Comment by pilzm** [comment]
Works great, thank you!

**Comment by llfbandit** [comment]
Thanks to you! This let me make another step forward for stable version.
