### ISSUE TITLE
Do not follow refs for discriminator properties

### ISSUE THREAD

**Issue by Dimitris-Christodoulou** [openapi4j/openapi4j#35]
**Is your feature request related to a problem? Please describe.**
When parsing the API we do the following to get a full document with all references inlined:
```
new OpenApi3Parser().parse(tempFile.toFile, false)
api.copy(api.getContext, true)
```
The API definition contains multiple schemas with discriminator properties like the one below:
```
components:
  responses:
    sampleObjectResponse:
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/Object1'
              - $ref: '#/components/schemas/Object2'
              - $ref: 'sysObject.json#/sysObject'
            discriminator:
              propertyName: objectType
              mapping:
                obj1: '#/components/schemas/Object1'
		obj2: '#/components/schemas/Object2'
                system: 'sysObject.json#/sysObject'
  …
  schemas:
    Object1:
      type: object
      required:
        - objectType
      properties:
        objectType:
          type: string
      …
    Object2:
      type: object
      required:
        - objectType
      properties:
        objectType:
          type: string
      …
```
The problem with flattening the above is that it no longer complies with the [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#discriminatorObject) because discriminator properties must be used in conjunction with a Schema **_ref_** and cannot be used with an inline schema.

Validating the above schema with a valid payload fails with a `NullPointerException` because the `DiscriminatorValidator` is [looking for a schema ref](https://github.com/openapi4j/openapi4j/blob/c8da658730bac34be82ac0502ef2fe19d9676ac1/openapi-schema-validator/src/main/java/org/openapi4j/schema/validator/v3/DiscriminatorValidator.java#L87).

**Describe the solution you'd like**
Do not inline refs if they are used as discriminator properties

**Describe alternatives you've considered**
At the moment we are working around it by not following refs at the top level and instead selectively following refs on the operation level using `Operation::copy`.

**Comment by llfbandit** [comment]
You are right about this.

So we should not follow the references in both cases: anyOf and oneOf with a driscrimator as a sibling node despite the `followRefs` flag.

Do you agree?

**Comment by Dimitris-Christodoulou** [comment]
> You are right about this.
> 
> So we should not follow the references in both cases: anyOf and oneOf with a driscrimator as a sibling node despite the `followRefs` flag.
> 
> Do you agree?

I agree but I think `allOf` should also be included because it is [supported by the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-21).

**Comment by llfbandit** [comment]
Oups, I thought only about the inheritance description.
Ok let's do this.

**Comment by llfbandit** [comment]
Can you validate this issue ?

**Comment by Dimitris-Christodoulou** [comment]
Validated. It seems to be fixed. Thanks.

**Comment by llfbandit** [comment]
Thanks to you!
