### ISSUE TITLE
Validation error on responses http status code ranges

### ISSUE THREAD

**Issue by tli-bw** [openapi4j/openapi4j#39]
**Describe the bug**
Http status code ranges (e.g. 5XX) in OpenAPI 3 `Responses object` do not validate successfully. 

**To Reproduce**
1. Add a status code range to a responses object in an existing OpenAPI spec i.e.
```
responses:
   "200":
      description: Success
   "5XX":
      description: Unexpected error
```
2. Attempt to validate spec using `OpenApi3Validator`
3. Validation error is displayed with message Invalid key `'5XX' in map 'default|\d\d\d\'`

**Expected behavior**
There should be no validation errors.

**Additional context**
[Status code ranges are allowed in OpenAPI 3](http://spec.openapis.org/oas/v3.0.0#patterned-fields-0).

**Comment by llfbandit** [comment]
Thank you for having spotted this bug.

Can you validate the fix available on latest snapshot?

**Comment by tli-bw** [comment]
Fix looks good! Thanks for addressing this so quickly.
