### ISSUE TITLE
Validate against discriminator-related "subclass" schemas

### ISSUE THREAD

**Issue by zhennTil** [openapi4j/openapi4j#46]
When using the `allOf` pattern with discriminators and referencing only the "superclass" (so to speak) from the operation (see example below,) it would be useful to validate not only against the superclass schema, but also the subclass schema.
I.e. if validating an instance against a schema that has a `discriminator` field, look for a schema in `#/components/schemas` that is defined with an `allOf` that contains a `$ref` to the original schema, _and_ whose name matches the discriminator value in the instance, and validate against that schema instead.

I'm not sure if this is on the edge of the validator's responsibility or the OpenAPI specification, but it seems reasonable enough. The last paragraph of the description at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#discriminatorObject is a little vague though.

Thoughts?

```yaml
paths:
  /discriminator:
    post:
      operationId: discriminator
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
    Dog:     # "Dog" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Dog`-specific properties
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Dog`
          properties:
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:     # "Cat" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Cat`-specific properties
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Cat`
          properties:
            hunts:
              type: boolean
            age:
              type: integer

```

**Comment by llfbandit** [comment]
You're right, OAS inheritance is fuzzy in current versions (and 3.0.3 or 3.1 give no further clues/possibilities for now). Cumulated with discriminator key there's a lot of holes in the specification.

For your request, this won't be possible as Pet has no idea of other schemas. On this point, the OAS is clear `The discriminator attribute is legal only when using one of the composite keywords oneOf, anyOf, allOf.` Discriminator key is dedicated to shortcut some potential heavy lookup on those collections to find the right schema and you're not specifying any.

I would do better on this, but I can't overlap the OAS.

**Comment by zhennTil** [comment]
Ah of course, I missed that sentence in the OAS. Thanks for the clarification! :)
