### ISSUE TITLE
relative url support in Server Object

### ISSUE THREAD

**Issue by seokgyo** [openapi4j/openapi4j#47]
**Describe the bug**
Hi,

url field in Server Object should allow a relative url. But it seems like not supported yet.

from the spec:
```
A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. Variable substitutions will be made when a variable is named in {brackets}.
```

**Comment by llfbandit** [comment]
Thank you for the report.
The issue should be fixed. Can you validate this on latest 0.7-SNAPSHOT?

Error reporting is just escaped for relative url as we can't truly validate it.

**Comment by seokgyo** [comment]
It works well.
Thanks a lot. 👍
