### ISSUE TITLE
AbsOpenApiSchema.copyMap() doesn't honor map type

### ISSUE THREAD

**Issue by hauner** [openapi4j/openapi4j#51]
**Describe the bug**

`AbsOpenApiSchema.copyMap()` does not honor the source map type. 

The properties of an `object` schema originally are stored in a `LinkedHashMap` to preserve the order of the properties. This is lost by `copyMap()`.

It happens when I try to resolve a ref schema like this:

    def resolved = schema.copy (api.context, true)

**Comment by llfbandit** [comment]
Thank you for the report.
I do force now `LinkedHashMap` creation to reflect Jackson behaviour.
This should be ok on 0.7-SNAPSHOT. Are you able to validate this change?

**Comment by hauner** [comment]
Thanks, works. The testcase on my end does not fail anymore. :-)
