### ISSUE TITLE
Map<String,Object> incorrectly validated

### ISSUE THREAD

**Issue by smhc** [openapi4j/openapi4j#64]
**Describe the bug**
Validating a Map<String,Object> implicitly converts the map to a JsonNode using a schema. However this causes values to be coerced to the correct type. This can mean numbers get converted to strings and validate as strings. It can also cause strings to be parsed as numbers, fail parsing, and be left as 'null'. This causes the validation errors to be incorrect or missing.

The use of a schema for conversion is also problematic as it does not cater for discriminators which can cause values to be converted to different types depending on context. 

**To Reproduce**
```
spec: 
{
  "properties": {
        "name":  { 
            "type": "string"
         }
   }
}

request body:
{
 name: 1234
}
```
Validate the body using a Map<String,Object> representation of the request.

**Expected behavior**

Expect that Java String objects get converted to JsonNode strings, irrespective of the schema. Likewise for Integer etc objects.

This can be worked around by manually converting to JsonNode:

```java
     ObjectMapper OBJECT_MAPPER = new ObjectMapper();
     JsonNode jsonNodeMap = OBJECT_MAPPER.convertValue(objMap, JsonNode.class);
     builder.body(Body.from(jsonNodeMap));
```

If this is too difficult to solve it may be best to deprecate the Map<String,Object> interface, as it seems quite incorrect.

**Comment by llfbandit** [comment]
Thanks for the report, now map is directly converted to JsonNode and more generally, content "primitives" (i.e. not object or array) are now mapped regardless what the type is supposed to be. Wrong content type is now converted to string node instead of null node for better error reports.

Are you able to confirm the fix in latest snapshot?

**Comment by smhc** [comment]
Thanks that appears to have resolved those simple test cases using strings and integers.

>  (i.e. not object or array) are now mapped regardless what the type is supposed to be.

Does this suggest that objects and arrays are mapped according to the spec rather than the data object type? I think there will be issues if you use the spec for anything during conversion without doing full validation.

The use of discriminators means the data is polymorphic and cannot be converted using the spec without doing full validation. A property may be a string or an object/hash, depending on the value of another property.

Is there any reason you can't inspect the object and see if it is a hash or a list rather than using the spec? The jackson libraries may have some helpers to do this.

**Comment by llfbandit** [comment]
I wrote this for other content types and parameters (cookies, query, ...) also combined with defined styles. Map<String, Object> as input is fine here.

For the others, I'll digg into it in a separate issue but it may be impossible to achieve. Let's take an exemple for a query parameter with exploded form style : `/users?id=5` without the schema we can't determine if it's a primitive or an array with a single value in the collection.
