### ISSUE TITLE
Chain custom validation

### ISSUE THREAD

**Issue by smhc** [openapi4j/openapi4j#75]
**Describe the bug**
Question (not a bug): Is it possible to chain custom validators to the original core validator?

In particular I have written a new "format" validator to trap 'date-time' and 'date' formats and record them (for later data conversion). I would like to then delegate the validation  to the original 'FormatValidator' behaviour for validation against other well-known formats.

**To Reproduce**
1. Create a 'format' validator as per https://github.com/openapi4j/openapi4j/tree/master/openapi-schema-validator
2. Validate a body with invalid values with respect to the 'format' value.

**Comment by llfbandit** [comment]
Hi,

There is no way to access core validators.
I suggest to declare a new keyword (`x-date` for example) in your Document Description for your specific needs then `format` keyword can be processed normally.

**Comment by smhc** [comment]
Unfortunately I have no control over the spec files. Although I could iterate the parsed schema and modify it in memory to add the extensions.

I think supporting custom formats without spec modification is desirable. The spec supports custom formats - so validating the added custom formats in addition to the standard ones will be a common use case.  Validating keywords other than 'format' will also likely want to fall back to the 'stock' validator after performing the overloaded operation. (e.g I will want to trap all 'type' keywords, but I would prefer to not re-implement the typevalidator).

Can the 'validate' function of the custom validator simply return a boolean which indicates whether openapi4j should proceed onto the core validator after processing? 

I can imagine you may want a 'preValidate' and 'postValidate' hook as well(?). The validation hooks are what differentiate openapi4j from other validators so it would be good to make them powerful. But at the least - a boolean which controls the chaining to the core validator would be sufficient.

**Comment by llfbandit** [comment]
I implemented a chaining behaviour for validators.
Now `validate` method returns a boolean to break or continue the chain.
You can have a look at the updated [README.md](https://github.com/openapi4j/openapi4j/tree/master/openapi-schema-validator#extensions) for further info.

Are you able to validate this in latest 0.8-SNAPSHOT?
Thanks

**Comment by smhc** [comment]
Thanks for the changes. I gave them a quick test and it appears to be working.

Another approach could be to pass the next validator in the chain to the validation function as a parameter. The custom validation function can then choose to call the next one or not. It would allow it to post process the validation results, e.g strip out certain errors from core validators. It does put the onus on the custom function to chain correctly however.

But the boolean return approach is likely to be adequate 90% of the time.
