### ISSUE TITLE
Per call context object available to custom validators.

### ISSUE THREAD

**Issue by smhc** [openapi4j/openapi4j#81]
**Is your feature request related to a problem? Please describe.**
I would like to be able to pass context to the custom validators per call.
I create and store an OperationValidator then call methods such as 'validateBody' on this. However my custom validation ideally needs to know whether it is validating a request or a response.

I can imagine other use cases where someone may want to make available the entire request or response object (or another object entirely) to the validators such that they can use this extra context for validation.

**Describe the solution you'd like**
Probably the most flexible solution is to support passing a generic 'Object' to the 'validateBody' etc validators which is pass around everywhere.
Alternatively there can be a generic object on "ValidationResults" that is already passed everywhere (will need to ensure this object is also added on any copies that are made in anyOf and oneOf validators).
It might be best to replace the existing ValidationResults with a new wrapper class:

```java
class ValidatingContext
{
   ValidationResults vr;
   
    Object customData;
    // or
    virtual Object getCustomData()
}
```

**Describe alternatives you've considered**
- A possible workaround can be to insert a dummy 'ValidationItem' at index 0 of the validation results. However the anyOf and oneOf validators create new ValidationResults objects for validation so don't have access to it.
- A singleton - however this is not thread safe.
- Walking up the schema to determine if there is a 'responseBody' or 'requestBody'.

**Additional context**
I can help work on a solution if you can give an idea of an approved design.

**Comment by llfbandit** [comment]
Sounds fair to me.
As a quick guess, I think the wrapper class (not convinced by `ValidatingContext` naming tho) is the only (clean) way to achieve this.

Maybe this should wait the closing of #80 to avoid many conflicts and get a readable PR?
I still need to add more tests and raise the code coverage.

**Comment by smhc** [comment]
I wrapped the ```ValidationResults``` with a delegate class, ```ValidationDetail```. This required a lot of renaming, perhaps not that clean.

Take a look at this diff if you can:
https://github.com/openapi4j/openapi4j/compare/master...smhc:validating_context

Alternative solution would be to simply support 'customData' on ValidationResults directly. But I think having it separate makes sense. It may be worth moving the 'crumbs' stuff into ValidationDetail as well - and keep the results only containing the results (```List<ValidationItem> items```).

**Comment by llfbandit** [comment]
Thinking further about `ValidationDetail` wrapper I've come to believe this will be an open door to low cohesion path.

So, new proposal, what about a new `DataContext<T>` object with a single `T get()` method as an input?

pros:
- fully generic (avoiding casting too)
- ability to add any methods in T complex object.
- enclosing delegate pattern (what for? I don't know but possible).
- no additional code to support on my side (mostly method signatures).
- no messy `ValidationResults` handling.
- cohesion.

cons:
- parameterize all schema validators with T is a requirement.
- adding 2 methods operation validator module, 1 to modify on SchemaValidator. (not really a cons...)

**Comment by smhc** [comment]
Is this change what you were thinking?  I haven't tested it, but I suppose it could work ok.

https://github.com/openapi4j/openapi4j/compare/master...smhc:data_context

It was my initial thought to add an extra param, but it seemed invasive. In the end it's probably cleaner.

**Comment by llfbandit** [comment]
I unthinkingly closed this issue, sorry for that (when merging of #84, that was not supposed to be published).

Are you able to tell if it suits your needs?

I reverted back to wrapper conception with, hopefully, a more meaningful naming.

**Comment by smhc** [comment]
I tested out the changes and they accomplish what I want, thanks for your help.

I may also need the ability to identify the exact node in the source at validation time. The crumbs get me 90% there, but arrays are problematic as we don't have the item number, and each item could be a different "shape". I will think about this some more, logging 'INFO' records and post processing may be adequate for these cases.

Do you have a date for releasing these changes (0.9) to maven central?

**Comment by llfbandit** [comment]
I'm aware of indexes.

The only thing that could be done is to append the index before 'items' crumb but also after the property in any adding a crumb instead of merging it.

This would result to something like:
foo.[1].bar...
foo.[1].<items>.bar...

[0].baz...
[0].<items>.baz...

Not sure if it's helpful.

**Comment by smhc** [comment]
I think something like this might be required. It's the only way to be sure to have the correct crumb for a model that is very dynamic per item. However it would quickly add up if there were thousands of entries in an array.

Perhaps the default should be to aggregate crumbs without indexes, and custom validators could have a way to flag adding items with their associated indexes. Or just a flag set in 'ValidationContext'.

In any case it's not relevant to this issue. I am happy to close this one and raise a new issue for the index problem.
