### ISSUE TITLE
ValidateHeaders fails when one httpStatus has headers

### ISSUE THREAD

**Issue by jalema** [openapi4j/openapi4j#88]
**Describe the bug**
I have one method response (202) with a header. The other responses don't have headers. When I have a 200 response the validator returns:
"Validation error(s) :
Response status '200', ranged or default has not been found. (code: 204)"

**To Reproduce**
1. API with a method with a response with header and another response with content type
2. Validate the return of the response with content type
3. The headers will not validate

**Expected behavior**
As the API does not declare any header for the response, the response should be valid

**Comment by llfbandit** [comment]
Hi and welcome,

Thanks for the report, I'll look into it.

**Comment by llfbandit** [comment]
Now, `OperationValidator` won't report the given error when status code has not been found in Document Description for headers and body in response.
=> Nothing to validate , so no error.

Can you confirm the changes in 0.9-SNAPSHOT?
Well... when sonatype will be back. The build status can be checked [here](https://travis-ci.org/github/openapi4j/openapi4j).

**Comment by jalema** [comment]
Thanks @llfbandit

The build failed. Can you review it please?

**Comment by llfbandit** [comment]
The build is good, it just fails when pushing snapshot to sonatype services. I can't do more until the service can be reached.
Here's the direct URL : https://oss.sonatype.org/content/repositories/snapshots/org/openapi4j/

**Comment by llfbandit** [comment]
Now published. Can you confirm the changes in 0.9-SNAPSHOT?

**Comment by jalema** [comment]
@llfbandit tested. Works fine! Thanks for your effort!

Cheers
