### ISSUE TITLE
Fail validation for unknown fields

### ISSUE THREAD

**Issue by denisMihaylov** [openapi4j/openapi4j#90]
I am trying to validate an input to a given schema but I would like the validation to fail if there are properties in the input that are not in the schema. Is this possible and if not are you planning to implement it?

**Comment by llfbandit** [comment]
Hi and welcome,

By default, Schema Object on OpenApi allows additional properties.

So, you have two options:
- modify your schema to include `additionalProperties: false` where needed (native solution),
- setup the option on `ValidationContext` with `setOption(ADDITIONAL_PROPS_RESTRICT, true)` to invert the default behaviour.
