### ISSUE TITLE
Unable to load refs when parsing with project in jar

### ISSUE THREAD

**Issue by colinchilds** [openapi4j/openapi4j#96]
I have multiple openapi files in my resources folder that reference each other. Attempting to parse them works just fine when running the code with my IDE, but as soon as I jar the project and run the jar, openapi4j is unable to process any refs. I am loading the swagger file like this:

```
URL url = Thread.currentThread().getContextClassLoader().getResource(filePath);
openAPI = new OpenApi3Parser().parse(url, false);
```

and my swagger file looks like this:

```
{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "My Service",
    "version" : "1.0.0"
  },
  "paths" : {
    "/endpoint" : { "$ref" :  "swagger2.json#/paths/get_endpoint" },
  }
}
```

**To Reproduce**
1. Reference another swagger file from your root swagger file in your project resources
2. Parse the root file and confirm it works correctly
3. Create a jar of your project, including resources
4. Run the jar

**Expected behavior**
The refs should evaluate, even though they are in a jar

**Comment by llfbandit** [comment]
Hi and welcome,

Thanks for the report, I can confirm the issue.
This fails because of URI class with `resolve()` method.

Time to change those URI to URL.

**Comment by llfbandit** [comment]
Are you able to validate this in latest 0.9-SNAPSHOT?

**Comment by colinchilds** [comment]
I was able to validate this works fine in the 0.9 snapshot. Thank you! Any estimate on when that could be released?

**Comment by llfbandit** [comment]
Thank you, release will be pushed tomorrow or early next week.
